export type PhotoTier = "thumb" | "display";

/**
 * Path convention for locally-hosted photos, generated by
 * scripts/process-images.ts into
 * public/photos/{thumb,display}/{basePath}/{photoId}.webp
 */
export function getPhotoPath(tier: PhotoTier, basePath: string, photoId: string): string {
  return `/photos/${tier}/${basePath}/${photoId}.webp`;
}

export function getPhotoPaths(basePath: string, photoId: string): { thumb: string; display: string } {
  return {
    thumb: getPhotoPath("thumb", basePath, photoId),
    display: getPhotoPath("display", basePath, photoId),
  };
}
