name: Update static content

on:
  push:
    paths:
      - 'content/**'

permissions:
  contents: write

jobs:
  thumbnails:
    runs-on: ubuntu-latest
    env:
      IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}
      IMAGE_KIT_PRIVATE_KEY: ${{ secrets.IMAGE_KIT_PRIVATE_KEY }}
      IMAGE_KIT_PUBLIC_KEY: ${{ secrets.IMAGE_KIT_PUBLIC_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate thumbnails
        id: static-generate-thumbnails
        continue-on-error: false
        run: npm run thumbnails

      - name: Update stats
        id: static-generate-thumbnails
        continue-on-error: false
        run: npm run extract-stats

      - name: Commit updated thumbnails and charts
        if: steps.static-generate-thumbnails.outcome == 'success' && steps.static-update-stats.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update thumbnails and/or chart data'

      - name: Trigger deployment
        if: steps.static-generate-thumbnails.outcome == 'success' && steps.static-update-stats.outcome == 'success'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-request
          client-payload: |
            {
              "triggered_by": "thumbnails",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}"
            }